Repository TeamSmil3y/PigeonPost, pull requests merged in 2023-11, with the labels that each got.

#40 :sparkles::white_check_mark: added automatic type conversion
  demo/app.py
  docs/pages/quickstart.rst
  src/pigeon/__main__.py
  src/pigeon/conf/manager.py
  src/pigeon/conf/registry.py
  src/pigeon/conf/settings.py
  src/pigeon/http/response.py
  src/pigeon/middleware/components/component.py
  src/pigeon/middleware/components/content_negotiation.py
  src/pigeon/middleware/components/mediafiles.py
  src/pigeon/middleware/components/staticfiles.py
  src/pigeon/middleware/conversion/__init__.py
  src/pigeon/middleware/conversion/converter.py
  src/pigeon/middleware/conversion/mime/__init__.py
  src/pigeon/middleware/conversion/mime/generators.py
  src/pigeon/middleware/conversion/mime/parsers.py
  src/pigeon/middleware/pipe.py
  src/pigeon/middleware/processing.py
  src/pigeon/middleware/views.py
  src/pigeon/scripts/__init__.py
  src/pigeon/scripts/_resources/app.py
  src/pigeon/scripts/_resources/settings.py
  src/pigeon/scripts/commands.py
  tests/middleware/components/test_content_negotiation.py
  tests/middleware/conversion/__init__.py
  tests/middleware/conversion/test_auto_type_conversion.py
  tests/middleware/test_views.py
  tests/resources/settings.py
  tests/testcases.py
Labels: :sparkles: new feature, :white_check_mark: tests

#42 ✨🏗️⚰️ ErrorHandler fully implemented
  src/pigeon/http/common.py
  src/pigeon/middleware/views.py
Labels: :sparkles: new feature

#43 Dev2
  src/pigeon/conf/manager.py
  src/pigeon/conf/settings.py
  src/pigeon/default/__init__.py
  src/setup.cfg
  tests/__init__.py
  tests/middleware/components/test_content_negotiation.py
  tests/middleware/components/test_host.py
  tests/middleware/conversion/test_auto_type_conversion.py
  tests/middleware/test_views.py
  tests/resources/settings.py
  tests/runner.py
  tests/setup_test.py
  tests/testcases.py
  tests/utils/__init__.py
Labels: :white_check_mark: tests

#46 Dev3
  demo/settings.py
  src/pigeon/__init__.py
  src/pigeon/core/__init__.py
  src/pigeon/core/app.py
Labels: :art: cleanup / prettify

#56 Feature/basic auth
  demo/app.py
  docs/pages/tutorial.rst
  src/pigeon/conf/manager.py
  src/pigeon/conf/settings.py
  src/pigeon/core/app.py
  src/pigeon/http/message.py
  src/pigeon/http/request.py
  src/pigeon/http/response.py
  src/pigeon/middleware/auth.py
  src/pigeon/middleware/conversion/converter.py
  src/pigeon/middleware/views.py
  tests/middleware/conversion/test_auto_type_conversion.py
  tests/middleware/test_views.py
  tests/setup_test.py
Labels: :sparkles: new feature, :lock: security
